// Better Auth database schema (Drizzle, Postgres).
//
// Generated by `pnpm auth:generate` (Better Auth CLI) — do not hand-edit the
// table definitions; regenerate after changing auth plugins/options. The four
// tables (user, session, account, verification) plus relations are required by
// email/password auth. Later phases (vault, pgvector) add their own tables here.

import { relations } from "drizzle-orm";
import {
  pgTable,
  text,
  timestamp,
  boolean,
  integer,
  jsonb,
  index,
  primaryKey,
} from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ─────────────────────────────────────────────────────────────────────────────
// Aegis vault — per-user data. Every row is scoped to a Better Auth user; the
// `id` mirrors the domain object's id (sample ids on seed, generated ids for
// user-created rows), so the primary key is composite (userId, id). Deleting a
// user cascades to wipe their entire vault.
//
// Date-ish fields are stored as ISO text (display/relative-date values, not
// queried as dates). String arrays use text[]; the trigger timeline uses jsonb.
// ─────────────────────────────────────────────────────────────────────────────

const userFk = () =>
  text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" });

// A vault "context item". `kind` discriminates how it was created and stored:
//   'file' — an uploaded file (PDF parsed to text, or an image stored as-is)
//   'note' — free-form markdown authored in-app (wishes, instructions, …)
// Both are chunked into documentChunk and become agent-retrievable. Notes keep
// their markdown source in `body` for round-trip editing; files have no body.
export const document = pgTable(
  "document",
  {
    userId: userFk(),
    id: text("id").notNull(),
    kind: text("kind").notNull().default("file"), // file | note
    category: text("category").notNull(),
    title: text("title").notNull(),
    fileName: text("file_name"), // null for notes
    body: text("body"), // markdown source for notes (null for files)
    notes: text("notes").notNull().default(""),
    sensitive: boolean("sensitive").notNull().default(false),
    uploadedAt: text("uploaded_at").notNull(),
    updatedAt: text("updated_at"),
    // Document pipeline (nullable so seeded sample docs / notes stay valid).
    storageKey: text("storage_key"),
    mimeType: text("mime_type"),
    sizeBytes: integer("size_bytes"),
    pageCount: integer("page_count"),
    status: text("status").notNull().default("ready"), // processing | ready | failed
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

// Searchable text pieces extracted from a document (one document -> many chunks).
// BM25 retrieval scores these, scoped to the owning user.
export const documentChunk = pgTable(
  "document_chunk",
  {
    userId: userFk(),
    id: text("id").notNull(),
    documentId: text("document_id").notNull(),
    chunkIndex: integer("chunk_index").notNull(),
    content: text("content").notNull(),
    tokenCount: integer("token_count"),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.id] }),
    index("document_chunk_user_doc_idx").on(t.userId, t.documentId),
  ],
);

export const policy = pgTable(
  "policy",
  {
    userId: userFk(),
    id: text("id").notNull(),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    policyNumber: text("policy_number").notNull(),
    coverageAmount: text("coverage_amount").notNull(),
    premium: text("premium").notNull(),
    renewalDate: text("renewal_date").notNull(),
    networkHospitals: text("network_hospitals").array(),
    claimContact: text("claim_contact").notNull(),
    claimSteps: text("claim_steps").array(),
    notes: text("notes").notNull().default(""),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

export const beneficiary = pgTable(
  "beneficiary",
  {
    userId: userFk(),
    id: text("id").notNull(),
    name: text("name").notNull(),
    relationship: text("relationship").notNull(),
    whatsapp: text("whatsapp").notNull(),
    verificationSecret: text("verification_secret").notNull().default(""),
    accessScope: text("access_scope").array().notNull().default([]),
    status: text("status").notNull().default("pending"),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

export const guardian = pgTable(
  "guardian",
  {
    userId: userFk(),
    id: text("id").notNull(),
    name: text("name").notNull(),
    relationship: text("relationship").notNull(),
    whatsapp: text("whatsapp").notNull(),
    role: text("role").notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

export const instruction = pgTable(
  "instruction",
  {
    userId: userFk(),
    id: text("id").notNull(),
    type: text("type").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull().default(""),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

export const contact = pgTable(
  "contact",
  {
    userId: userFk(),
    id: text("id").notNull(),
    name: text("name").notNull(),
    role: text("role").notNull(),
    phone: text("phone").notNull(),
    notes: text("notes").notNull().default(""),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

// Structured secrets (logins, account numbers, PINs). Deliberately SHIELDED
// from the agent: never chunked/indexed and exposed by no agent tool. Stored
// plaintext for now — field-level encryption is a fast follow.
export const credential = pgTable(
  "credential",
  {
    userId: userFk(),
    id: text("id").notNull(),
    label: text("label").notNull(),
    username: text("username").notNull().default(""),
    secret: text("secret").notNull().default(""),
    url: text("url").notNull().default(""),
    notes: text("notes").notNull().default(""),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at"),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

// A tokenized access link that lets an (unauthenticated) beneficiary reach the
// owner's vault agent in Legacy Mode. The token is the bearer credential; the
// Mastra server middleware resolves it server-side and gates on the owner's
// vault being in `legacy` mode. ownerId is never supplied by the client.
export const accessGrant = pgTable(
  "access_grant",
  {
    token: text("token").primaryKey(),
    ownerId: text("owner_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    beneficiaryId: text("beneficiary_id").notNull(),
    createdAt: text("created_at").notNull(),
    expiresAt: text("expires_at"),
    revokedAt: text("revoked_at"),
  },
  (t) => [index("access_grant_owner_idx").on(t.ownerId)],
);

// 1:1 vault profile — the owner's "protecting" line plus the per-user
// trigger/check-in state machine (previously a global in-memory singleton).
export const vaultProfile = pgTable("vault_profile", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  protecting: text("protecting").notNull().default(""),
  mode: text("mode").notNull().default("everyday"),
  timeline: jsonb("timeline").notNull().default([]),
  cadenceDays: integer("cadence_days").notNull().default(14),
  lastCheckinAt: text("last_checkin_at"),
  missedCount: integer("missed_count").notNull().default(0),
  threshold: integer("threshold").notNull().default(3),
});

// Maps a Telegram account to a vault. Owners link their own account (role
// 'owner'); beneficiaries link via a legacy grant token (role 'beneficiary',
// grantToken set). The worker (scripts/telegram.ts) resolves an inbound sender
// through this table, then re-checks beneficiary grants on every message
// (lib/telegram/resolve.ts). userId is always the vault OWNER's id.
export const telegramLink = pgTable(
  "telegram_link",
  {
    telegramUserId: text("telegram_user_id").primaryKey(),
    chatId: text("chat_id").notNull(),
    role: text("role").notNull(), // 'owner' | 'beneficiary'
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    grantToken: text("grant_token"), // null for owners
    displayName: text("display_name").notNull().default(""),
    createdAt: text("created_at").notNull(),
  },
  (t) => [index("telegram_link_user_idx").on(t.userId)],
);

// One-time pairing codes an owner generates in the app to bind their Telegram
// account (`/start <code>`). Consumed on first use; short-lived.
export const telegramPairCode = pgTable("telegram_pair_code", {
  code: text("code").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  expiresAt: text("expires_at").notNull(),
  usedAt: text("used_at"),
});
